[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = [
    'pip install -r backend/requirements.txt'
]

[phases.build]
cmds = [
    'python setup_database.py'
]

[start]
cmd = 'cd backend && python app.py'